### PR TITLE
feat: Add nix flake support

### PR DESCRIPTION
**Pull request by acaloiaro**
Thanks for creating exactly what I was looking for!

I'm happy to maintain nix support in my own fork, but if you'd like to add it upstream, think of this PR as a conversation starter. 

Ideally, the version and hash in `default.nix` are bemped whenever there is a release via github action. I have an action that'll fetch the latest tag and swap it into `default.nix` with `sed`, but I haven't automated hash calculation yet. 

If you're interested in this PR, I'll add that functionality. 

Also, let me know if you have any general nix questions and how this PR makes it possible to use your package in nix/nixos.

Cheers!

### CODE REVIEW

**Comment by dobicinaitis** [comment]
Hey, thanks for the PR! It gave me a nudge to finally check out Nix :slightly_smiling_face:

While doing so, I noticed that the Nix package manager already includes an entry for the upstream [tailwindcss](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/tailwindcss/default.nix) binary. With a bit of copy/paste magic, it could be used to add `tailwindcss-extra`.

What are your thoughts on this? Wouldn't a PR in [Nixpkgs](https://github.com/NixOS/nixpkgs) be more beneficial? It could help others seeking the same solution in discovering it more easily.

**Comment by acaloiaro** [comment]
> Hey, thanks for the PR! It gave me a nudge to finally check out Nix 🙂
> 
> While doing so, I noticed that the Nix package manager already includes an entry for the upstream [tailwindcss](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/tailwindcss/default.nix) binary. With a bit of copy/paste magic, it could be used to add `tailwindcss-extra`.

Indeed, this is what I used until I brought in the daisyUI dependency. 

> What are your thoughts on this? Wouldn't a PR in [Nixpkgs](https://github.com/NixOS/nixpkgs) be more beneficial? It could help others seeking the same solution in discovering it more easily.

I agree, it would be far more beneficial. Although, were I to open a PR against nixpkgs, the solution I'd propose would be different. 

For nixpkgs, I don't think I would propose simply adding `daisyui` to `tailwindcss`, or even adding `tailwind-cli-extra` as it's too niche to be generally useful. Ideally, the package in nixpkgs would allow the embedded 3rd party depedencies to be declared. 

Though, I don't have enough experience with nix/nixpkgs to know whether that's practical, or even possible, given its goal of reproducible builds. I believe the 3rd party packages that it's built with would have to be part of the package's source so that they can be added to the package's hash. So I'm not sure that this concept can be generalized in a way that's less niche. I'll continue looking into the viability of a generalized solution -- it may be possible with an overlay. 

But that's all to say -- I proposed the change to your package because I wasn't prepared to solve the problem more generally. It's a one-off fix to solve my immediate problem. But I won't be shocked if my needs expand beyond daisyui. I'm happy to keep these changes in my fork for now. Feel free to close this PR if you'd rather this package remain the simple and precise fix that it already is.

**Comment by acaloiaro** [comment]
I looked into this a bit further. The standalone tailwind CLI build process depends on [vercel-pkg](https://github.com/vercel/pkg), which needs to download `Node` binaries as part of its build process. This breaks nix's build sandboxing, which prevents network connections during build. The sandbox can be disabled, but it's there for a good reason.

**Comment by dobicinaitis** [comment]
I don't mind adding Nix support to this repo. We would just need to incorporate automatic updating of hashes for all architectures. If I'm not mistaken, the `fetchurl` method can also accept a "pure" `sha256` value instead of the Nix `hash`. If that's the case, then updating the values within the release workflow would be easy.

Do you mind explaining how you will run/install the Nix package from this repo? Do the files have to reside in the root of the project, or can they be moved to a subdirectory like `packaging/nix`? I might add other types, e.g., `snaps`, later, so building out a clean structure would be nice.

**Comment by acaloiaro** [comment]
@dobicinaitis Sounds good. I'll get this polished up in the coming week or so. 

To "run" this package as a nix flake, with `flake.nix` at the top-level directory looks like: 

- `nix run github:dobicinaitis/tailwind-cli-extra`

With `flake.nix` in `packaging`, it looks like:

- `nix run github:dobicinaitis/tailwind-cli-extra?dir=packaging`

I don't see this organization done often, but it is valid. I would describe it as non-idiomatic. At the same time, I don't love multiple nix-related files polluting the top-level directory with their presence. So I understand the inclination to hide them.

The alternative is to hide `default.nix` away in `packaging` and keep `flake.nix` at the top level to keep the run syntax minimal.

**Comment by dobicinaitis** [comment]
Thanks for the extra details @acaloiaro! In this case, just keep the Nix files at the top level. Once you have finished polishing them, if you wish, I can add the version and hash updating bits to the release workflow.

**Comment by larstvei** [comment]
Hi! I am very interested in using this, and crossing my fingers for a merge :)

**Pull request closed without merging**
